(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,602,147,131],[0,735,100,143],[249,602,81,147],[149,602,98,189],[249,751,64,101],[0,0,160,600],[162,0,160,600]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.skyscraperbrusselsprouts = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.skyscrapercinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.skyscrapercranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.skyscraperpotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.skyscraperstuffing = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.skyscrapertable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.whitetable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.youtakethecredit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgIAJQgDgEAAgFQAAgEADgEQAEgDAEAAQAFAAAEADQADAEAAAEQAAAFgDAEQgEADgFAAQgEAAgEgDg");
	this.shape.setTransform(55.2,15.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AACA/IgEAAIgFgBQgEgBAAgEIAAhcQAAgBAAAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAACACIABAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgYAAQgEAAgCACQgBABAAAEIAABbQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_1.setTransform(47.4,10.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AAABBIgEAAQgEAAgDgEIAAh5QABAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAIAEgBIAEgBIAEAAQAFAAACAEIAAB5IgDADIgEABg");
	this.shape_2.setTransform(39.4,10.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("Ag0A/IgFgBQAAgBgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAhyQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIAvAAIAMABIANAEQAMAEAKAIQAJAJAFALQADAGABAGQABAHAAAGQAAAOgFAMIgGALIgJAJIgKAHIgLAFQgMAFgNAAgAgigmQgCACAAADIAABFQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAIAEACIAXAAQAIAAAIgDQAIgDAGgFQAGgFAEgIQADgHAAgKQAAgIgDgIQgEgHgGgGQgGgFgIgDQgIgDgIAAIgWAAQgDAAgDACg");
	this.shape_3.setTransform(29.9,10.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgqA/IgEgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAIgCAEIAAARQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(16.7,10.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AAfBAIgCgBIgDgCIgCgBIgVghIgDgEQgDgCgDABIgQAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAABAAABIAAAeQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgEACIgFAAIgEAAQgEAAgCgCQgCgBAAgEIAAhzQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAIADgBIA1AAQAKAAAIADQAIADAHAGQAFAFAEAIQADAHAAAKQAAALgEAHQgEAFgEAEIgJAHQgEADgBADIABADIAEAHIAIAKIAHAKIADAGQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgFADIgEAAgAgZgoQgDACAAAEIAAAcQAAADADABQACACADAAIAZAAQAFAAAEgBQAFgBADgCQADgDADgEQABgEAAgGQAAgKgHgFIgIgEIgJgBIgZAAIgFABg");
	this.shape_5.setTransform(4.1,10.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgFBAIgNgDIgLgGIgKgIIgIgKIgGgLQgGgMAAgOQAAgNAGgMIAGgLIAIgJQAJgKAMgFIANgDQAGgBAHAAIAOABIAOAEQAHADAGAFQAGAEAEAGIABACQAAAEgDACIgFADIgDAEQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAQgCAAgDgDIgGgFQgEgEgGgDQgGgCgJAAQgIAAgIADQgIAEgGAFQgGAGgDAJQgDAIAAAHQAAAJADAIQADAIAGAFQAGAHAIADQAIAEAIAAQAJAAAJgEQAIgEAGgHIAFgBIAEABIAFADIAEAEQAAAAABABQAAAAAAABQAAABABAAQAAABAAAAIgBADIgLAKQgFAEgHACQgHAEgHABQgHACgHgBIgNgBg");
	this.shape_6.setTransform(-9.6,10.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgqA/IgEgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAABABIABADIAAAFIAAAEIgBAEIgDADIhBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAIgCAEIAAARQAAAAAAABQAAABAAAAQAAABABAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_7.setTransform(-27.1,10.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgsBAIgEgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIAAh4IADgCIAEgCIAEAAIAFAAQAFAAACAFIAAAoQAAABAAAAQAAABABABQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAABAAIArAAQADAAACgCQADgCAAgDIAAgoQACgEADAAIAIgBIAGABIAEAEIgBB3QgBAEgEAAIgHAAIgGAAQgDgBgBgDIAAgsQAAgBgBAAQAAgBAAgBQAAAAgBgBQAAAAgBgBQgCgCgCAAIgqAAQgDAAgCADQgDACAAADIAAArQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAIgEABIgFABg");
	this.shape_8.setTransform(-40.5,10.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AACA/IgDAAIgHgBQgCgBAAgEIAAhcQAAgBgBAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgJAAIgGAAQgDAAgBgDQgCgCAAgDIAAgEIABgFIACgDIADgBIBXAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgaAAQgCAAgDACQgCABAAAEIAABbQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgDACg");
	this.shape_9.setTransform(-52.7,10.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgqA/IgEgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAIgDACIgCAEIAAARQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(40.8,-11.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAdBAQgDAAgBgCIgggwIgEgDIgFgBQgDAAgDACQgEACAAADIAAAnQAAABAAABQAAABAAAAQAAABgBAAQAAABgBAAIgEACIgFAAIgFABQgHAAAAgGIAAh2IADgDIAEgBIAEAAIAEAAQAGAAACAEIAAAoQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAIAFACQADAAACgDIAjgqIACgCIADAAIAEABIAFADIAEADIABADIgBAEIgfAjIgBADIAAAEIAAADIABACIAoA2IAAACIABACQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABIgEACIgFACIgFAAg");
	this.shape_11.setTransform(28.7,-11.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AAuA/IgHAAQgDgBgCgDIgHgRIgCgDQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgqAAIgCAAIgCABIgCACIgBABIgGARIgDACIgDABIgEABIgDAAIgEAAIgEAAIgDgCIgBgCIAzh2QAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIAxB1IAAABQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgEABIgFABgAgBgTIgBABIgBAEIgDAGIgDAHIgDAGIgCAGIgBACIABADIACABIAZAAIACgBIABgCIgCgGIgEgJIgEgLIgDgGIgDgBg");
	this.shape_12.setTransform(15.8,-11.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AACA/IgEAAIgFgBQgEgBAAgEIAAhcQAAgBAAAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAACACIABAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgYAAQgEAAgCACQgBABAAAEIAABbQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_13.setTransform(4.5,-11.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgVA9QgKgEgHgHQgIgHgEgKIgEgKIgBgMIAAgiIABgiQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAIAEgCIAFAAIAEgBIAGACQADABAAADIAABAQAAAIACAGQACAHAEAFQAEAFAGADQAGADAHAAQAIAAAGgDQAGgDAEgFQAFgFACgHQACgGAAgIIAAhAQAAgDACgCIAGgBIAFAAIAEAAIAEACQABABAAAAQAAABAAAAQABABAAAAQAAABAAABIAABEIgBAMIgEAKQgEAKgIAHQgHAHgKAEQgKAEgMAAQgKAAgLgEg");
	this.shape_14.setTransform(-13.1,-11.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgNBAIgNgEIgLgGIgKgIQgJgIgFgMQgDgGgBgHQgCgGAAgHIACgMQABgHADgGQAFgMAJgJIAKgHIALgGIANgEIANgBIANABIAOAEQAMAFAJAIQAJAJAFAMQAGAMgBANQAAAHgBAGQgBAHgDAGQgFAMgJAIQgJAJgMAFIgOAEIgNABIgNgBgAgPgnQgIADgGAGQgGAGgDAIQgEAIAAAIQAAAJAEAIQADAIAGAGQAGAGAIADQAHADAIAAQAJAAAHgDQAIgDAGgGQAGgGADgIQAEgIAAgJQAAgIgEgIQgDgIgGgGQgGgGgIgDQgHgDgJAAQgIAAgHADg");
	this.shape_15.setTransform(-27.5,-11.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgEBBIgDAAIgCgCIgBgCIAAgtIgCgHIgDgHIgkg3IAAgBIABgEIAEgDIAFgCIAEgBIAEABIADACIAZApIADADIACAAIADgBIACgCIAZgpIAEgDIAEgBIAEABIAFACIAEADQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAABIAAABIgkA4IgEAHIAAADIgBADIAAAtQgCAEgEAAIgGABg");
	this.shape_16.setTransform(-40.6,-11.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.youtakethecredit, new cjs.Rectangle(-60,-21.9,120,43.8), null);


(lib.whitetable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.whitetable();
	this.instance.parent = this;
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitetable_1, new cjs.Rectangle(-80,-300,160,600), null);


(lib.wellmakethe = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape.setTransform(64.8,24.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_1.setTransform(45.1,20.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABAAQAAABAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_2.setTransform(29,22.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_3.setTransform(4.1,24.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AA4B+IgHgBQgHgDgRgUIgHgKIgDgEQgqg2gDAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAHIAAAIIABAkQABAKACADIAKAFQAIAEAAAGQAAAGgJADQgIADgXAAQgaAAgIgDQgJgCAAgIQAAgGAJgDIAEgCQAFgCACgJQABgJAAgUIAAgVIAAgbIAAgUIgBhBQgBgPgDgEQgCgBgHgDIgGgBIgHgEIgBgEQAAgFADgDQAEgCAMgFIAXgHIASgCQAFAAACAEQADADAAAIIgBAhIgBAtIAAAqIAAAJQABABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAHgEIANgKIAQgQQAEgFAAgDQAAgCgGgDQgFgDAAgFQAAgIAIgEQAJgDAYAAQAQAAAIADQAIAEAAAHQAAAIgNADQgMADgGADQgGADgPAPIgCADIgGAGIgCADQAAADAPAVIACACIAeAkQAMAPAHAEQAEADALAEQALADAAAHQAAAHgIAEQgIADgSAAg");
	this.shape_4.setTransform(-14,20.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AAfBRIgJgJIgIAEQgVAOgVAAQgZAAgQgOQgQgPAAgYQABgbATgPQAVgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgRAAgKAIQgKAIAAAPQgBAOAKAIQAJAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgHgIQgGgIgMAAQgIAAgHADQgIAEgGAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAANAFQAOAFAIAKQAFAGACALQACAKAAAZIAAA3QAAAKACAFQACAEADABIAGACQALADgBAGQAAAIgLAHQgMAGgPAAQgHAAgJgJg");
	this.shape_5.setTransform(-33.3,24.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("ABBB6QgKgDAAgIQAAgHALgEIAHgEQAEgCABgIQABgHAAgXIAAgJIAAhJIgBgsIgWA5QgzCEgLAAQgFAAgKgSQgKgSgYg4IgmhXIgBBEIgBAvIABAgQABAHADACIAHAEQALAEAAAHQAAAIgJADQgJADgVAAQgTAAgIgDQgJgEAAgHQAAgGAKgEQAJgFABgDQACgJADgsQADgsAAg2IAAgGQAAgSgCgGQgBgGgEgDIgIgDQgMgFAAgHQAAgGAIgDQAIgDAZAAIAZABIAHABQADADAMAfIAKAYIAFAMQAqBoADAAQADAAAQgmQAPgkAWg9IADgKQAGgTAGgGQADgDAGgBIAYgCQAXAAAIADQAIADAAAGQAAAIgKADIgFACQgFADgCAHQgCAHAAAaIACBiQACAsABAHQABAEAIADIAEABIAHAEQACACAAAEQAAAIgKADQgKADgcAAQgaAAgJgDg");
	this.shape_6.setTransform(-58.4,20.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgcB8QgJgCAAgIQAAgFAHgDIAJgGQADgCABgKIABgjIAAgbIAAggIAAgNQAAgsgBgMQgCgNgEgCIgKgDQgLgEAAgFQAAgFADgCQAEgDAMgFIAXgHIARgCQAFAAACADQADAEAAAIIgBANQgCA9AAA+IABA8QABAMADADIAKAFQAIAEAAAGQAAAHgJACQgIADgXAAQgZAAgIgDg");
	this.shape_7.setTransform(34.5,-20.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgcB8QgJgCAAgIQAAgFAHgDIAJgGQADgCABgKIABgjIAAgbIAAggIAAgNQAAgsgBgMQgCgNgEgCIgKgDQgLgEAAgFQAAgFADgCQAEgDAMgFIAXgHIARgCQAFAAACADQADAEAAAIIgBANQgCA9AAA+IABA8QABAMADADIAKAFQAIAEAAAGQAAAHgJACQgIADgXAAQgZAAgIgDg");
	this.shape_8.setTransform(24.8,-20.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AgCAyIgMhLIgBgDIAAgEQAAgIAEgFQAEgEAHAAQAIAAAEAEQAEAFAAAIIAAAFIgBACIgMBLg");
	this.shape_9.setTransform(17.3,-27.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_10.setTransform(5.2,-16.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAYA8IglhfQgLgfgHgPQgHgOgGgFIgKgEQgIgDAAgHQgBgHAJgCQAHgDAhAAQAgAAAIADQAIACAAAHQAAAHgNAFIgCAAQgEACgCACQgBADAAAEQAAAGAIAXIAdBLIAMAcQAEAHACAAQACAAAEgFIALgaIAEgHQAjhVABgLQAAgFgDgEQgDgEgGgCIgDgCQgLgEABgHQgBgHAIgCQAGgDAcAAQAcAAAHADQAHACAAAHQAAAHgKAEIgIAEQgMAIgWA7IgOAjIgiBRIgGAQQgKAbgIAAQgJAAgZhDgAhGBxIgDgGQgWgwgihYIgPgpIgLgVQgFgHgFgDIgFgCQgLgEAAgHQAAgHAJgCQAHgDAhAAQAhAAAIADQAIACAAAHQAAAHgOAFIAAAAQgFACgCACQgCADAAAEQAAAFAHAVIAdBMIANAfQAEAGADAAQADAAAEgIIAIgUQAEgLAJAAQALAAAAALIgDALIgVA3IgGANQgLAcgHAAQgGAAgFgOg");
	this.shape_11.setTransform(-21.7,-20.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethe, new cjs.Rectangle(-76,-43,152,86.1), null);


(lib.turkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgSATQgIgIAAgLQAAgLAIgHQAHgIALAAQAMAAAHAIQAIAHAAALQAAALgIAIQgIAIgLAAQgLAAgHgIg");
	this.shape.setTransform(55.5,10.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape_1.setTransform(42.2,7.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_2.setTransform(24.3,4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AA4B/IgHgCQgHgDgRgUIgHgKIgDgEQgqg2gDAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAHIAAAHIABAlQABAKACAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgaAAgIgDQgJgDAAgHQAAgGAJgDIAEgCQAFgCACgJQABgIAAgUIAAgWIAAgbIAAgUIgBhAQgBgRgDgCQgCgDgHgCIgGgBIgHgDIgBgGQAAgEADgDQAEgDAMgEIAXgGIASgDQAFAAACAEQADACAAAJIgBAhIgBAtIAAArIAAAJQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAHgEIANgKIAQgRQAEgEAAgDQAAgBgGgEQgFgDAAgFQAAgJAIgCQAJgEAYAAQAQAAAIAEQAIADAAAHQAAAHgNADQgMAEgGADQgGADgPAPIgCACIgGAHIgCADQAAADAPAVIACACIAeAkQAMAPAHAEQAEADALAEQALADAAAHQAAAIgIADQgIADgSAAg");
	this.shape_3.setTransform(6.2,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_4.setTransform(-10.3,3.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AAlBYQgCgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgDADQgIAIgKAFQgJAEgNAAQgOAAgKgFQgMgFgHgJQgJgKgDgOQgDgOAAgkIAAgMIAAgMIAAgEQAAgOgCgEQgCgEgGgCIgIgCQgJgDAAgGQAAgEADgDQAEgDAMgEIAYgHIASgCQAFAAABADQADAEAAAHIgBAHIgCBBQAAAiAIAOQAHANASAAQATAAAIgRQAJgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgKgDAAgGQABgEADgDQADgDAMgEIAYgHIASgCQAFAAACADQACADAAAIIAAAKIgCBGIAAAeIABALQABAHAJAEIAAAAIADABQAKADAAAGQAAAEgDADQgDACgHADIgZAIQgMADgGAAQgFAAgDgCg");
	this.shape_5.setTransform(-27.7,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgjB7QgLgDABgIQAAgHAJgDQAJgEACgCQACgDABgdIABhRIgBgtIgBgcQAAgFgDgBQgEgCgGAAIgIAAQgMAAgGADQgHADgFAHIgGALIgFAMIgEAFQgEACgDAAQgFAAgCgEQgCgFgBgKQABgXAFgOQAFgOAIAAIACAAQAOACAVAAIBlAAQAVAAANgCIADAAQAIAAAFAOQAGAOAAAXQAAAKgCAFQgDAEgFAAIgHgCIgFgFIgEgMIgGgLQgFgHgHgDQgHgDgLAAIgIAAQgGAAgEACQgCABgBAFIgCAcIAAAtIABBRQABAdACADQACACAJAEQAJADAAAHQABAIgLADQgJADgbAAQgaAAgJgDg");
	this.shape_6.setTransform(-49.1,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.turkey, new cjs.Rectangle(-62.3,-22.5,124.7,45.1), null);


(lib.stuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgSATQgIgIAAgLQAAgLAIgHQAIgIAKAAQAMAAAHAIQAIAHAAALQAAALgIAIQgIAIgLAAQgKAAgIgIg");
	this.shape.setTransform(68.1,10.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgMBaIgTgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAQgOQAPgPAZAAIALABIANADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgDADgFAAQgEAAgEgDQgEgDgFgIQgGgMgHgEQgIgDgJAAQgKgBgFAGQgHAFAAAKQABAHAGAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_1.setTransform(55.7,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AhABxQgWgOABgTQAAgIAEgGQAFgGAKAAQAGAAAFAEQADAFADAIQAEAMALAIQALAHAVAAQAWAAAPgJQAPgJABgNQgBgIgFgFQgGgEgLAAIgUABIgaACQgeAAgRgLQgRgKAAgOQAAgJAHgIQAFgIANgHQgKgJgFgLQgFgLAAgOQAAgcAVgSQAWgTAgAAIARABIAbAGQAGAAAHgEQAIgDALgHIAFAFIACAGQABAHgGAHQgFAHgLAFIAGAOIACAOQAAAdgWASQgUARgiAAIgSgBIgQgEIgFAHIgCAGQgBAIAJAEQAIAEARAAIAZgCIAbgCQAYAAANAKQANAKABASQgBAcgbASQgbASgpAAQggAAgXgNgAgchVQgJALAAARQAAASAJALQAIAKAPAAQANAAAKgKQAKgLAAgSQAAgRgKgLQgJgLgOAAQgNAAgKALg");
	this.shape_2.setTransform(39.9,6.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgHAAgTQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAJQgEAIgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVgBQANAAALAGQAMAFAIAKQAIAJADANQADAOAAAbIAAAWIAAAMIAAAKQAAAMACAFQACAFAEACIAEADQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape_3.setTransform(19.7,3.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAEgCACgGQACgGAAgNIAAgMIAAgNIAAgSQAAgcgCgHQgBgIgDgCIgIgDQgKgDAAgGQAAgEACgDQAEgDAHgDIAagIIASgEQAFAAACAEQABADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAGACQAJAEAAAGQABAHgJADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAHAGQAIAHAAAJQAAAJgIAHQgIAHgMAAQgLAAgHgGg");
	this.shape_4.setTransform(4.5,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgwB8QgJgDAAgHQABgFAHgDIAFgCQAEgCACgGQACgGAAgOIAAgRIAAhTIgUAAQgEAAgBgBQgCgCAAgFIAAgEQAAgFACgBQACgCAEAAIASAAIgCgOIgBgMQAAgbAQgOQAQgPAbAAQAUAAANAJQAMAJAAAOQAAAIgFAEQgEAEgJAAQgFAAgEgCQgFgDgDgEIgDgHQgGgMgKAAQgHAAgDAEQgEAEAAAHIAEAUQADAPAAAMIAZAAQAFAAACABQABACAAAFIAAAEQAAAEgBACQgCACgFAAIgZAAIAABYQABAXABAGQABAHAEACIAHACQAKAEAAAHQAAAGgIADQgJADgZAAQgYAAgJgDg");
	this.shape_5.setTransform(-3.7,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgwB8QgJgDABgHQAAgFAHgDIAFgCQAEgCACgGQABgGABgOIAAgRIAAhTIgUAAQgEAAgCgBQgBgCAAgFIAAgEQAAgFACgBQABgCAFAAIASAAIgCgOIgBgMQAAgbAQgOQAQgPAbAAQAVAAAMAJQAMAJAAAOQAAAIgEAEQgFAEgJAAQgFAAgEgCQgFgDgDgEIgDgHQgGgMgLAAQgGAAgDAEQgEAEAAAHIAEAUQADAPAAAMIAZAAQAFAAACABQABACAAAFIAAAEQAAAEgBACQgDACgEAAIgZAAIAABYQAAAXACAGQABAHAEACIAHACQAKAEAAAHQAAAGgJADQgIADgZAAQgYAAgJgDg");
	this.shape_6.setTransform(-13.5,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AAmBYQgDgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgCADQgIAIgLAFQgKAEgMAAQgOAAgLgFQgLgFgIgJQgIgKgDgOQgEgOAAgkIAAgMIAAgMIAAgEQAAgOgCgEQgBgEgHgCIgGgCQgKgDAAgGQAAgEAEgDQADgDAMgEIAXgHIATgCQAEAAACADQACAEAAAHIAAAHIgCBBQABAiAHAOQAHANASAAQATAAAJgRQAIgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgJgDAAgGQgBgEAEgDQADgDANgEIAWgHIASgCQAGAAACADQACADAAAIIgBAKIgCBGIABAeIABALQABAHAJAEIABAAIADABQAJADAAAGQAAAEgDADQgDACgIADIgYAIQgMADgGAAQgFAAgCgCg");
	this.shape_7.setTransform(-30.4,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_8.setTransform(-46.6,2.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgqB8QgTgDgNgIQgGgEgFgOQgEgPAAgUQAAgIADgEQADgEAFAAQAIAAAJAQIAEAHQALATANAJQANAIASAAQASAAANgLQANgLAAgRQAAgYgygWIgGgDQgqgRgNgQQgOgPAAgYQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgFIAGgBQAEAAADADQAEACADAHQAGAKAEAMQADALAAAJQAAAFgDAEQgDADgEAAQgKAAgIgNIgDgCQgKgNgLgGQgMgHgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAJQAKAKAkAPIAHADQAfANAOAMQAJAJAFALQAFAMAAAOQAAAjgYAUQgZAUgrAAQgVAAgTgFg");
	this.shape_9.setTransform(-62.9,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.stuffing, new cjs.Rectangle(-74.9,-22.5,149.8,45.1), null);


(lib.sides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgSATQgIgIAAgLQAAgLAIgHQAIgIAKAAQALAAAIAIQAIAHAAALQAAALgIAIQgIAIgLAAQgKAAgIgIg");
	this.shape.setTransform(41.8,10.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_1.setTransform(29.5,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_2.setTransform(12.9,4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AhLBpQgUgYAAglQAAgrAXgZQAXgbAlAAIAMACQAFABADAEQADAEAAAEQAAAKgLAAIgFgBIgEAAQgTAAgMAQQgLAOAAAcQAAAdAMASQANATATAAQASAAAKgKQAKgLAAgTIAAgvIAAhPQAAgMgDgFQgCgFgGgCIgFgBQgLgEAAgFQAAgFAEgDQAFgEANgEIATgGIAQgCQAGAAADADQACAEAAAIIAAAIIgCBqIABBIQABARADACIAMAEQAJACAAAGQAAAIgZAJIgRAEIgNABQgFAAgCgDQgCgCAAgGIAAgJIgBgCIgBgCIgFAEIgIAGQgKAHgJAEQgKAEgKAAQghAAgUgXg");
	this.shape_3.setTransform(-5.8,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQACgGAAgNIgBgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAIgDIAagIIARgEQAEAAACAEQACADABAIIAAAKIgBAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_4.setTransform(-21.6,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgqB8QgTgDgNgIQgGgEgFgOQgEgPAAgUQAAgIADgEQADgEAFAAQAIAAAJAQIAEAHQALATANAJQANAIASAAQASAAANgLQANgLAAgRQAAgYgygWIgGgDQgqgRgNgQQgOgPAAgYQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgFIAGgBQAEAAADADQAEACADAHQAGAKAEAMQADALAAAJQAAAFgDAEQgDADgEAAQgKAAgIgNIgDgCQgKgNgLgGQgMgHgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAJQAKAKAkAPIAHADQAfANAOAMQAJAJAFALQAFAMAAAOQAAAjgYAUQgZAUgrAAQgVAAgTgFg");
	this.shape_5.setTransform(-36.6,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sides, new cjs.Rectangle(-48.6,-22.5,97.3,45.1), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAXAwIgXhMIAAAAIgWBMIgOAAIgchfIAOAAIAVBLIAXhLIANAAIAXBLIAAAAIAVhLIAOAAIgcBfg");
	this.shape.setTransform(35.8,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKAxIgJgDQgJgDgHgHQgHgHgEgJQgEgJAAgLQAAgKAEgKQAEgJAHgGQAHgHAJgEIAJgCIAKgBQALAAAJADIAJAFIAHAGQAHAGAEAJQAEAKAAAKQAAALgEAJQgEAJgHAHIgHAGIgJAEQgJAEgLAAIgKgBgAgOgjQgHAEgEAFQgFAFgDAHQgCAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAHADAHAAQAIAAAHgDQAHgDAEgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgEgFgHgEQgHgDgIAAQgHAAgHADg");
	this.shape_1.setTransform(23.4,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXAwIgxhNIAABNIgOAAIAAhfIASAAIAxBMIAAhMIANAAIAABfg");
	this.shape_2.setTransform(12.5,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AASAwIgXgrIgPAAIAAArIgNAAIAAhfIAfAAIAMACQAGABAEADQAFADADAFQADAFAAAIQAAAKgHAHIgHAEIgKADIAbAsgAgUgFIAQAAIAHgBIAHgCQAEgCABgDQACgDAAgEQAAgFgCgDIgEgEIgHgDIgHAAIgRAAg");
	this.shape_3.setTransform(0.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfAwIAAhfIA9AAIAAAMIgvAAIAAAdIAsAAIAAAKIgsAAIAAAgIAxAAIAAAMg");
	this.shape_4.setTransform(-8.1,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpAwIAAhfIAhAAQAIAAAJADQAJADAIAFQAHAGAFAJIADAKIABALIgBALIgDAKIgGAIIgGAHQgIAGgJADQgLADgGAAgAgcAkIARAAQAJAAAGgCQAHgDAGgEQAFgFADgHIACgHIABgIIgBgHIgCgIQgDgGgFgFQgGgEgHgDQgGgCgJAAIgRAAg");
	this.shape_5.setTransform(-17.3,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASAwIgXgrIgPAAIAAArIgNAAIAAhfIAfAAIAMACQAGABAEADQAFADADAFQADAFAAAIQAAAKgHAHIgHAEIgKADIAbAsgAgUgFIAQAAIAHgBIAHgCQAEgCABgDQACgDAAgEQAAgFgCgDIgEgEIgHgDIgHAAIgRAAg");
	this.shape_6.setTransform(-26.4,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKAxIgJgDQgJgDgHgHQgHgHgEgJQgEgJAAgLQAAgKAEgKQAEgJAHgGQAHgHAJgEIAJgCIAKgBQALAAAJADIAJAFIAHAGQAHAGAEAJQAEAKAAAKQAAALgEAJQgEAJgHAHIgHAGIgJAEQgJAEgLAAIgKgBgAgOgjQgHAEgEAFQgFAFgDAHQgCAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAHADAHAAQAIAAAHgDQAHgDAEgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgEgFgHgEQgHgDgIAAQgHAAgHADg");
	this.shape_7.setTransform(-36.7,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-44.5,-10.3,89,20.6), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175,-175,350,350);


(lib.holidaymainstable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.skyscrapertable();
	this.instance.parent = this;
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainstable, new cjs.Rectangle(-80,-300,160,600), null);


(lib.holidaymainsstuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.skyscraperstuffing();
	this.instance.parent = this;
	this.instance.setTransform(-32,-50.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsstuffing, new cjs.Rectangle(-32,-50.5,64,101), null);


(lib.holidaymainspotatoes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.skyscraperpotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-49,-94.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainspotatoes, new cjs.Rectangle(-49,-94.5,98,189), null);


(lib.holidaymainscinnamonrolls = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.skyscrapercinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-50,-71.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscinnamonrolls, new cjs.Rectangle(-50,-71.5,100,143), null);


(lib.holidaymainsbrusselsprouts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.skyscraperbrusselsprouts();
	this.instance.parent = this;
	this.instance.setTransform(-73.5,-65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsbrusselsprouts, new cjs.Rectangle(-73.5,-65.5,147,131), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgLjgt8IXHAAMAAABb5I3HAAg");
	this.shape.setTransform(0,0,1.074,1.018);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-80.5,-300.5,161,601), null);


(lib.desserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgSATQgIgIAAgLQAAgLAIgHQAIgIAKAAQAMAAAHAIQAIAHAAALQAAALgIAIQgIAIgLAAQgKAAgIgIg");
	this.shape.setTransform(66.7,10.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgMBaIgTgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAQgOQAPgPAZAAIALABIANADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgDADgFAAQgEAAgEgDQgEgDgGgIQgFgMgHgEQgIgDgJAAQgKgBgFAGQgHAFAAAKQABAHAGAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_1.setTransform(54.4,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_2.setTransform(40.9,2.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_3.setTransform(28.5,3.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_4.setTransform(12.4,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_5.setTransform(-4.3,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgDADgFAAQgDAAgEgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_6.setTransform(-19.2,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_7.setTransform(-35.8,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AglB8IgWAAIgOAAIgOAAQgWAAgGgCQgGgDgBgHQAAgHAJgEQAKgDABgCQACgEACgaIAChDIgCg/QgCgbgCgDQgBgCgKgEQgJgEAAgHQAAgHAIgCQAHgEAUAAIAQABIARAAIAXgBIATAAQBBAAAiAhQAjAhAAA9QAAA8gkAfQgjAfhEAAgAgmhiQgHADgCAFQgCAHgCAUIgBA1IABBBQACAbACAGQABAFAMAEQALADAQAAQAnAAAUgXQAUgYAAgxQAAgzgXgaQgWgbgqAAQgOAAgJACg");
	this.shape_8.setTransform(-58.3,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.desserts, new cjs.Rectangle(-73.5,-22.5,147.1,45.1), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqdCrIAAlVIU7AAIAAFVg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-67,-17.1,134.1,34.3), null);


(lib.cranberriesholidaymains = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.skyscrapercranberries();
	this.instance.parent = this;
	this.instance.setTransform(-40.5,-73.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cranberriesholidaymains, new cjs.Rectangle(-40.5,-73.5,81,147), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.stuffings = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.stuffing();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.stuffings, new cjs.Rectangle(-74.9,-22.5,149.8,45.1), null);


// stage content:
(lib.wideskyscraperholidaymains = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_50 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		
		console.log("this frame works");
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.rollover_color.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.rollover_color.gotoAndPlay(13);
		}
	}
	this.frame_180 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(50).call(this.frame_50).wait(130).call(this.frame_180).wait(325));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(82.2,302,0.797,0.919,0,0,0,0.1,0.4);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(505));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(505));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(82.1,300);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(496));

	// logo
	this.instance_2 = new lib.logokale("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,37.1,0.003,0.003,0,0,0,0,17.5);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({startPosition:0},0).to({scaleX:0.29,scaleY:0.29,y:42.1,alpha:1},6,cjs.Ease.get(1)).to({scaleX:0.27,scaleY:0.27,y:41.7},7,cjs.Ease.get(1)).wait(483));

	// desserts
	this.instance_3 = new lib.desserts();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,243.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(188).to({alpha:1},10).wait(40).to({alpha:0},5).wait(262));

	// sides
	this.instance_4 = new lib.sides();
	this.instance_4.parent = this;
	this.instance_4.setTransform(80,243.5);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(148).to({alpha:1},10).wait(30).to({alpha:0},5).wait(312));

	// stuffing
	this.instance_5 = new lib.stuffings();
	this.instance_5.parent = this;
	this.instance_5.setTransform(80,243.5);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(108).to({alpha:1},10).wait(30).to({alpha:0},5).wait(352));

	// turkey
	this.instance_6 = new lib.turkey();
	this.instance_6.parent = this;
	this.instance_6.setTransform(80,243.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(19).to({alpha:1},10).wait(79).to({alpha:0},5).wait(392));

	// you-take-the-credit
	this.instance_7 = new lib.youtakethecredit();
	this.instance_7.parent = this;
	this.instance_7.setTransform(77.7,298.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(505));

	// well-make-the-turkey
	this.instance_8 = new lib.wellmakethe();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80,181.9);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(19).to({alpha:1},10).wait(209).to({alpha:0},5).wait(262));

	// order-now
	this.instance_9 = new lib.ordernow();
	this.instance_9.parent = this;
	this.instance_9.setTransform(80,361.3);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(29).to({alpha:1},10).wait(466));

	// cta-rectangle
	this.instance_10 = new lib.ctarectangle();
	this.instance_10.parent = this;
	this.instance_10.setTransform(79,360.9);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(29).to({alpha:1},10).wait(466));

	// potatoes
	this.instance_11 = new lib.holidaymainspotatoes();
	this.instance_11.parent = this;
	this.instance_11.setTransform(111,398.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(77).to({alpha:1},10).wait(418));

	// brussel-sprouts
	this.instance_12 = new lib.holidaymainsbrusselsprouts();
	this.instance_12.parent = this;
	this.instance_12.setTransform(86.5,534.5);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(69).to({alpha:1},10).wait(426));

	// cranberries
	this.instance_13 = new lib.cranberriesholidaymains();
	this.instance_13.parent = this;
	this.instance_13.setTransform(40.5,458.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(61).to({alpha:1},10).wait(434));

	// cinnamon-rolls
	this.instance_14 = new lib.holidaymainscinnamonrolls();
	this.instance_14.parent = this;
	this.instance_14.setTransform(110,71.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(53).to({alpha:1},10).wait(442));

	// stuffing
	this.instance_15 = new lib.holidaymainsstuffing();
	this.instance_15.parent = this;
	this.instance_15.setTransform(32,50.5);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(45).to({alpha:1},10).wait(450));

	// table
	this.instance_16 = new lib.holidaymainstable();
	this.instance_16.parent = this;
	this.instance_16.setTransform(80,300);

	this.instance_17 = new lib.whitetable_1();
	this.instance_17.parent = this;
	this.instance_17.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_17},{t:this.instance_16}]}).wait(505));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(79.9,300,164.4,603.3);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;